import { SurveyDefinition } from '../types';

export const surveys: Record<string, SurveyDefinition> = {
	customer_experience: {
		surveyKey: 'customer_experience',
		surveyName: 'Customer Experience',
		surveyPath: '/surveys/customer-experience',
		version: 1,
		questions: [
			{
				helpText: 'Example: N123AB',
				id: 'tail_number',
				label: 'Tail Number',
				maxLength: 10,
				minLength: 3,
				placeholder: 'N123AB',
				required: true,
				showLabel: true,
				type: 'text_input',
			},
      {
				helpText: 'Example: CAA',
				id: 'what_brought_you_to_north_star_jet',
				label: 'What bruoght you to North Star Jet?',
				placeholder: 'Select an option',
				required: true,
				showLabel: true,
        options: ['CAA', 'Contract Fuel', 'Prices', 'Customer Service', 'Word of Mouth', 'Other'],
				type: 'dropdown_select_one',
			},
      {
				helpText: 'Example: Pop Corn',
				id: 'what_is_your-favorite_amenity',
				label: 'What is your favorite amenity?',
				placeholder: 'Select an option',
				required: true,
				showLabel: true,
        options: ['Pop Corn', 'Merch', 'Coffee'],
				type: 'dropdown_select_one',
			},      
			{
				helpText: 'Example: Yes',
				id: 'would_you_return',
				label: 'Would you return?',
				placeholder: 'Select an option',
				required: true,
				showLabel: true,
        options: ['Yes', 'No'],
				type: 'dropdown_select_one',
			},
			{
				helpText: 'Overall score.',
				id: 'how_was_our_customer_service_stars',
				label: 'How was our Customer Service?',
				max: 5,
				min: 1,
				required: true,
				showLabel: false,
				type: 'stars',
			},
      {
				helpText: 'How was our service?',
				id: 'how_was_our_customer_service_text',
				label: 'How was our Customer Service?',
				maxLength: 500,
				minLength: 3,
				placeholder: 'What about us stood out to you?',
				required: true,
				showLabel: true,
				type: 'text_box',
			},
      {
				helpText: 'Overall score.',
				id: 'how_were_the_amenities_stars',
				label: 'How were the amenities?',
				max: 5,
				min: 1,
				required: true,
				showLabel: false,
				type: 'stars',
			},
      {
				helpText: 'How were our services?',
				id: 'how_were_the_amenities_text',
				label: 'How were the amenities?',
				maxLength: 500,
				minLength: 3,
				placeholder: 'Did any amenities stand out to you?',
				required: true,
				showLabel: true,
				type: 'text_box',
			},
      {
				helpText: 'Overall score.',
				id: 'how_did_you_like_our_prices_stars',
				label: 'How did you like our prices?',
				max: 5,
				min: 1,
				required: true,
				showLabel: false,
				type: 'stars',
			},
      {
				helpText: 'How were our services?',
				id: 'how_did_you_like_our_prices_text',
				label: 'How did you like our prices?',
				maxLength: 500,
				minLength: 3,
				placeholder: 'How do we compare?',
				required: true,
				showLabel: true,
				type: 'text_box',
			},
		],
	},
		fbo_workshop_survey: {
		surveyKey: 'fbo_workshop_survey',
		surveyName: 'FBO Workshop Survey',
		surveyPath: '/surveys/fbo-workshop-survey',
		version: 1,
		questions: [
			{
				helpText: 'Example: N123AB',
				id: 'tail_number',
				label: 'Tail Number',
				maxLength: 10,
				minLength: 3,
				placeholder: 'N123AB',
				required: true,
				showLabel: true,
				type: 'text_input',
			},
		]
	}
}
