import { SurveyDefinition } from '../types';

export const surveys: Record<string, SurveyDefinition> = {
  customer_experience: {
    surveyKey: 'customer_experience',
    surveyName: 'Customer Experience',
    surveyPath: '/surveys/customer-experience',
    version: 1,
    questions: [
      {
        id: 'header',
        label:
          '**Customer Experience Survey**',
        showLabel: true,
        required: false,
				header: true,
				showLine: false,
        type: 'question_base',
      },
      {
        helpText: 'Example: N123AB',
        id: 'question_1',
        label: 'Tail Number',
        maxLength: 10,
        minLength: 3,
        placeholder: 'N123AB',
        required: true,
				header: false,
				showLine: false,
        showLabel: true,
        type: 'text_input',
      },
      {
        helpText: 'Example: CAA',
        id: 'question_2',
        label: 'What brought you to North Star Jet?',
        placeholder: 'Select an option',
        required: true,
				header: false,
				showLine: false,
        showLabel: true,
        options: [
          { caa: 'CAA' },
          { contract_fuel: 'Contract Fuel' },
          { prices: 'Prices' },
          { customer_service: 'Customer Service' },
          { word_of_mouth: 'Word of Mouth' },
          { other: 'Other' },
        ],
        type: 'dropdown_select',
      },
      {
        helpText: 'Example: Pop Corn',
        id: 'question_3',
        label: 'What is your favorite amenity?',
        placeholder: 'Select an option',
        required: true,
				header: false,
				showLine: false,
        showLabel: true,
        options: [
          { pop_corn: 'Pop Corn' },
          { merch: 'Merch' },
          { coffee: 'Coffee' },
        ],
        type: 'dropdown_select',
      },
      {
        helpText: 'Example: Yes',
        id: 'question_4',
        label: 'Would you return?',
        placeholder: 'Select an option',
        required: true,
				header: false,
				showLine: false,
        showLabel: true,
        options: [{ yes: 'Yes' }, { no: 'No' }],
        type: 'dropdown_select',
      },

      // Customer Service (stars + text)
      {
        helpText: 'Overall score.',
        id: 'question_5_rating',
        label: 'How was our Customer Service?',
        max: 5,
        min: 1,
        required: true,
				header: false,
				showLine: false,
        showLabel: false,
        type: 'stars',
      },
      {
        helpText: 'How was our service?',
        id: 'question_5',
        label: 'How was our Customer Service?',
        maxLength: 500,
        minLength: 3,
        placeholder: 'What about us stood out to you?',
        required: true,
				header: false,
				showLine: false,
        showLabel: true,
        type: 'text_box',
      },

      // Amenities (stars + text)
      {
        helpText: 'Overall score.',
        id: 'question_7_rating',
        label: 'How were the amenities?',
        max: 5,
        min: 1,
        required: true,
				header: false,
				showLine: false,
        showLabel: false,
        type: 'stars',
      },
      {
        helpText: 'How were our services?',
        id: 'question_7',
        label: 'How were the amenities?',
        maxLength: 500,
        minLength: 3,
        placeholder: 'Did any amenities stand out to you?',
        required: true,
				header: false,
				showLine: false,
        showLabel: true,
        type: 'text_box',
      },

      // Prices (stars + text)
      {
        helpText: 'Overall score.',
        id: 'question_9_rating',
        label: 'How did you like our prices?',
        max: 5,
        min: 1,
        required: true,
				header: false,
				showLine: false,
        showLabel: false,
        type: 'stars',
      },
      {
        helpText: 'How were our services?',
        id: 'question_9',
        label: 'How did you like our prices?',
        maxLength: 500,
        minLength: 3,
        placeholder: 'How do we compare?',
        required: true,
				header: false,
				showLine: false,
        showLabel: true,
        type: 'text_box',
      },
    ],
  },

  fbo_workshop_survey: {
    surveyKey: 'fbo_workshop_survey',
    surveyName: 'FBO Workshop Survey',
    surveyPath: '/surveys/fbo-workshop-survey',
    version: 1,
    questions: [
      // Objective
			 {
        id: 'header',
        label:
          '**FBO Workshop Survey**',
        showLabel: true,
        required: false,
				header: true,
				showLine: false,
        type: 'question_base',
      },
      {
        id: 'objective',
        label:
          '**Objective:** The goal of the FBO survey is to evaluate the effectiveness of the leadership team by gathering employee feedback on communication, decisionmaking, vision, teamwork, operational changes and support. The survey aims to identify leadership strengths, uncover areas for improvement, and assess alignment with company values and culture. Insights gained will help guide organizational development, enhance transparency, strengthen employee engagement, and ensure leaders are equipped to drive mission success.',
        showLabel: true,
        required: false,
				header: false,
				showLine: false,
        type: 'question_base',
      },
      // Instructions
      {
        id: 'instructions',
        label:
          '**Instructions:** Thank you for taking the time to provide feedback. Your input is essential in helping us strengthen our leadership practices and create a better workplace environment for the entire team. The survey is 100% anonymous. Please answer honestly, your candid feedback helps us improve and perform to the highest standards. For each question: Select the response that best represents your experience or opinion. Although not required, but highly encouraged, extra space has been provided to express any desired comment to each selected question.',
        showLabel: true,
        required: false,
				header: false,
				showLine: false,
        type: 'question_base',
      },

      // Q1
      {
        helpText: '',
        id: 'question_1',
        label:
          '1. How effectively do team members collaborate and support one another in completing work?',
        required: true,
				header: false,
				showLine: false,
        showLabel: true,
        options: [
          { very_effectively: 'Very effectively' },
          { effectively: 'Effectively' },
          { moderately_effectively: 'Moderately effectively' },
          { slightly_effectively: 'Slightly effectively' },
          { not_effectively: 'Not effectively' },
        ],
        type: 'rating',
      },
      {
        helpText: 'Example: Describe a recent instance that shows collaboration or support.',
        id: 'question_1_comment',
        label: 'Please give a specific example:',
        maxLength: 600,
        minLength: 0,
        placeholder: 'Share why you chose this rating.',
        required: false,
				header: false,
				showLine: false,
        showLabel: true,
        type: 'text_box',
      },

      // Q2
      {
        helpText: '',
        id: 'question_2',
        label: '2. How effectively does your direct leadership support you in your role?',
        required: true,
				header: false,
				showLine: false,
        showLabel: true,
        options: [
          { very_effectively: 'Very effectively' },
          { effectively: 'Effectively' },
          { moderately_effectively: 'Moderately effectively' },
          { slightly_effectively: 'Slightly effectively' },
          { not_effectively: 'Not effectively' },
        ],
        type: 'rating',
      },
      {
        helpText: 'Example: Coaching, resourcing, scheduling, recognition, or barrier removal.',
        id: 'question_2_comment',
        label: 'Please give a specific example:',
        maxLength: 600,
        minLength: 0,
        placeholder: 'Share why you chose this rating.',
        required: false,
				header: false,
				showLine: false,
        showLabel: true,
        type: 'text_box',
      },

      // Q3
      {
        helpText: '',
        id: 'question_3',
        label:
          '3. How clear and effective is communication within your team and across other NSJ departments?',
        required: true,
				header: false,
				showLine: false,
        showLabel: true,
        options: [
          { very_clear_and_effective: 'Very clear and effective' },
          { clear_and_effective: 'Clear and effective' },
          { somewhat_clear_and_effective: 'Somewhat clear and effective' },
          { unclear_and_ineffective: 'Unclear and ineffective' },
          { very_unclear_and_ineffective: 'Very unclear and ineffective' },
        ],
        type: 'rating',
      },
      {
        helpText:
          'Example: Shift handoffs, dispatch updates, email/Teams clarity, briefings, etc.',
        id: 'question_3_comment',
        label: 'Please give a specific example:',
        maxLength: 600,
        minLength: 0,
        placeholder: 'Share why you chose this rating.',
        required: false,
				header: false,
				showLine: false,
        showLabel: true,
        type: 'text_box',
      },

      // Q4
      {
        helpText: '',
        id: 'question_4',
        label: '4. How would you describe your overall morale and motivation at work?',
        required: true,
				header: false,
				showLine: false,
        showLabel: true,
        options: [
          { very_high: 'Very high' },
          { high: 'High' },
          { moderate: 'Moderate' },
          { low: 'Low' },
          { very_low: 'Very low' },
        ],
        type: 'rating',
      },
      {
        helpText: 'Example: Recognition, workload, schedule, training, culture, career path.',
        id: 'question_4_comment',
        label: 'Can you describe why:',
        maxLength: 600,
        minLength: 0,
        placeholder: 'Share why you chose this rating.',
        required: false,
				header: false,
				showLine: false,
        showLabel: true,
        type: 'text_box',
      },

      // Q5
      {
        helpText: '',
        id: 'question_5',
        label:
          '5. How well do you feel you are able to be productive in your role with the tools, resources, training, and expectations provided?',
        required: true,
				header: false,
				showLine: false,
        showLabel: true,
        options: [
          { very_well: 'Very well' },
          { well: 'Well' },
          { adequately: 'Adequately' },
          { poorly: 'Poorly' },
          { very_poorly: 'Very poorly' },
        ],
        type: 'rating',
      },
      {
        helpText: 'Example: GSE availability, systems access, SOP clarity, training, staffing.',
        id: 'question_5_comment',
        label: 'Can you describe why:',
        maxLength: 600,
        minLength: 0,
        placeholder: 'Share why you chose this rating.',
        required: false,
				header: false,
				showLine: false,
        showLabel: true,
        type: 'text_box',
      },

      // Q6
      {
        helpText: '',
        id: 'question_6',
        label:
          '6. How well does NorthStar Jet function overall in enabling you to perform your job successfully? (Module 5)',
        required: true,
				header: false,
				showLine: false,
        showLabel: true,
        options: [
          { extremely_well: 'Extremely well' },
          { well: 'Well' },
          { adequately: 'Adequately' },
          { poorly: 'Poorly' },
          { very_poorly: 'Very poorly' },
        ],
        type: 'rating',
      },
      {
        helpText:
          'Example: Cross-team coordination, policies, leadership consistency, processes.',
        id: 'question_6_comment',
        label: 'Can you describe why:',
        maxLength: 600,
        minLength: 0,
        placeholder:
          'Share why you chose this rating.',
        required: false,
				header: false,
				showLine: false,
        showLabel: true,
        type: 'text_box',
      },

      // Additional Comments (question id per your rule)
      {
        helpText: 'Anything else you’d like leadership to know.',
        id: 'question_7',
        label: 'Additional Comments',
        maxLength: 2000,
        minLength: 0,
        placeholder:
          'Share any other feedback, suggestions, or examples you think would help improve our operations, culture, or customer service.',
        required: false,
				header: false,
				showLine: true,
        showLabel: true,
        type: 'text_box',
      },

      // Scoreboard intro (non-interactive)
      {
        id: 'scoreboard_intro_header',
        label:
          '**FBO Scoreboard Ideas**',
        showLabel: true,
        required: false,
				header: false,
				showLine: true,
        type: 'question_base',
      },
			{
        id: 'scoreboard_intro1',
        label:
          'The FBO Leadership Team is seeking creative ideas to showcase the hard work and accomplishments of the entire FBO staff.',
        showLabel: true,
        required: false,
				header: false,
				showLine: false,
        type: 'question_base',
      },
			{
        id: 'scoreboard_intro2',
        label:
          'The goal is to highlight the value and dedication demonstrated by the team across all areas of operation.\nPlease review the scoreboard ideas listed below and select as many as you’d like—there is no limit to the number of choices you can make. If you have additional suggestions that are not listed, feel free to add your own ideas.',
        showLabel: true,
        required: false,
				header: false,
				showLine: false,
        type: 'question_base',
      },

						{
        id: 'scoreboard_intro_instructions',
        label:
          '**Instructions:** Please review the scoreboard ideas listed below and select as many as you’d like—there is no limit to the number of choices you can make. If you have additional suggestions that are not listed, feel free to add your own ideas.',
        showLabel: true,
        required: false,
				header: false,
				showLine: true,
        type: 'question_base',
      },
      // Q8 – Ground Services Performed
      {
        helpText:
          'Select as many ideas as you’d like—the goal is to showcase the team’s hard work and accomplishments.',
        id: 'question_8',
        label: '**Ground Services Performed** (select all that apply)',
        placeholder: 'Select one or more',
        required: false,
				header: false,
				showLine: false,
        showLabel: true,
        options: [
          { number_of_lavs_serviced: 'Number of Lavs Serviced' },
          { number_of_gpus_used: 'Number of GPUs Used' },
          { potable_water_service_completed: 'Potable Water Service Completed' },
          { belt_loader_operations_completed: 'Belt Loader Operations Completed' },
          { call_outs_performed: 'Call-Outs Performed' },
          { transient_hangar_services_provided: 'Transient Hangar Services Provided' },
        ],
        type: 'check_box',
      },

      // Q9 – Ramp Fueling Operations
      {
        helpText:
          'Select as many ideas as you’d like—the goal is to showcase the team’s hard work and accomplishments.',
        id: 'question_9',
        label: '**Ramp Fueling Operations** (select all that apply)',
        placeholder: 'Select one or more',
        required: false,
				header: false,
				showLine: false,
        showLabel: true,
        options: [
          { number_of_aircraft_fueled_nsj_ramp: 'Number of Aircraft Fueled (NSJ Ramp)' },
          { number_of_aircraft_serviced_nsj_ramp: 'Number of Aircraft Serviced (NSJ Ramp)' },
          { number_of_gse_fuelings_performed: 'Number of GSE Fuelings Performed' },
          { number_of_nsj_gallons_pumped: 'Number of NSJ Gallons Pumped' },
          { number_of_airline_gallons_pumped: 'Number of Airline Gallons Pumped' },
          { number_of_airlines_serviced: 'Number of Airlines Serviced' },
          { number_of_accepted_fuel_loads: 'Number of Accepted Fuel Loads' },
          { number_of_gallons_delivered: 'Number of Gallons Delivered' },
          { number_of_fueler_top_offs_completed: 'Number of Fueler Top-Offs Completed' },
        ],
        type: 'check_box',
      },

      // Q10 – Seasonal / De-Ice Operations
      {
        helpText:
          'Select as many ideas as you’d like—the goal is to showcase the team’s hard work and accomplishments.',
        id: 'question_10',
        label: '**Seasonal / De-Ice Operations** (select all that apply)',
        placeholder: 'Select one or more',
        required: false,
				header: false,
				showLine: false,
        showLabel: true,
        options: [
          { number_of_aircraft_de_iced: 'Number of Aircraft De-Iced' },
          { total_gallons_pumped_all_operations: 'Total Gallons Pumped (All Operations)' },
        ],
        type: 'check_box',
      },

      // Q11 – Programs, Training & Admin
      {
        helpText:
          'Select as many ideas as you’d like—the goal is to showcase the team’s hard work and accomplishments.',
        id: 'question_11',
        label: '**Programs, Training & Admin** (select all that apply)',
        placeholder: 'Select one or more',
        required: false,
				header: false,
				showLine: false,
        showLabel: true,
        options: [
          { award_program_winners: 'Award Program Winners' },
          { flight_school_hours_flown_monthly_ytd: 'Flight School Hours Flown (Monthly & YTD)' },
          {
            flight_school_progress_updates_solos_certifications:
              'Flight School Progress Updates (Solos & Certifications)',
          },
          { training_completed: 'Training Completed' },
          { level_1_nata: 'Level 1 – NATA' },
          { level_2_airlines: 'Level 2 – Airlines' },
          { level_3_nsj: 'Level 3 – NSJ' },
          { employee_spotlights_updated: 'Employee Spotlights Updated' },
          { nsj_testing_center_activity_recorded: 'NSJ Testing Center Activity Recorded' },
        ],
        type: 'check_box',
      },
			{
        helpText: 'What other ideas do you have?',
        id: 'scoreboard_suggestions',
        label: 'Scoreboard Suggestions',
        maxLength: 2000,
        minLength: 0,
        placeholder:
          'Feel free to add your own scoreboard suggestions!',
        required: false,
				header: false,
				showLine: false,
        showLabel: true,
        type: 'text_box',
      },

      // Closing note (non-interactive)
      {
        id: 'closing_note1',
        label:
          '**From the FBO Leadership**, Thank you for input. This information will be reviewed together as a team, with the goal of identifying shared opportunities to deliver the highest level of customer service as the most unified, highly qualified FBO in the Northwest.',
        showLabel: true,
        required: false,
				header: false,
				showLine: true,
        type: 'question_base',
      },
			{
        id: 'closing_note2',
        label:
          'The results of this survey will be shared and discussed during the upcoming annual FBO leadership development workshop. Thank You',
        showLabel: true,
        required: false,
				header: false,
				showLine: false,
        type: 'question_base',
      },
    ],
  },
	feedback:{
		surveyKey: 'feedback',
    surveyName: 'App Feedback',
    surveyPath: '/surveys/feedback',
    version: 1,
    questions: [
      {
        id: 'header',
        label:
          '**App Feedback Survey**',
        showLabel: true,
        required: false,
				header: true,
				showLine: false,
        type: 'question_base',
      },
      {
        helpText: '',
        id: 'bugs',
        label: 'Did you encounter any bugs?',
        maxLength: 10,
        minLength: 3,
        placeholder: 'Bugs... 𖢥',
        required: true,
				header: false,
				showLine: false,
        showLabel: true,
        type: 'text_box',
      },
      {
        helpText: '',
        id: 'improvements',
        label: 'What would you suggest to improve the app or experience?',
				maxLength: 10,
        minLength: 3,
				placeholder: 'Pizza...',
        required: true,
				header: false,
				showLine: false,
        showLabel: true,
        type: 'text_box',
      },
			{
        helpText: '',
        id: 'general_feedback',
        label: 'General Feedback',
				maxLength: 10,
        minLength: 3,
				placeholder: 'Tell us...',
        required: true,
				header: false,
				showLine: false,
        showLabel: true,
        type: 'text_box',
      },
      
    ],
  },

	
};
